version: '3.8'

services:
  # api:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=5000
  #     - PGUSER=developer
  #     - PGHOST=db
  #     - PGPORT=5432
  #     - PGPASSWORD=supersecretpassword
  #     - PGDATABASE=openmusicapi
  #   depends_on:
  #     - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=openmusicapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: